#!/bin/bash
# Generated by grain — do not edit by hand. See docs/design.md, "The
# controller VM" and "Secrets on /data", and docs/runbook.md's first-time
# setup checklist. Delivered as cloud-init NoCloud user-data, which runs a
# raw shebang script as-is via the scripts-user module — same mechanism
# provision/sandbox.sh uses.
#
# What this script does NOT do, on purpose, matching "no secret is ever
# baked into an image or a provisioning script" (docs/design.md, "Secrets on
# /data"):
#   - it never writes a GitHub token, a GCP service-account key, the repo
#     allowlist, or automation.json — those are placed by hand, once, per
#     docs/runbook.md's first-time setup checklist;
#   - it never deploys this repo's own source onto the box. `grain` has no
#     third-party dependencies (see pyproject.toml — stdlib only), so the
#     only thing missing to invoke `python3 -m grain.cli` is the source tree
#     itself at /opt/grain, and getting it there needs a credential this
#     script has no business holding (this repo's remote is not public).
#     Deploy it by hand, with your own credentials: e.g. `git clone
#     <your-remote> /opt/grain` (the directory is created below, empty, so
#     there's an obvious place to put it).
set -eux

GCE_METADATA_SERVER_VERSION="4.2.5"
# Matches Cluster().controller_ip for the default subnet (10.100.0.0/24) —
# see grain/inventory.py. Edit this if the deployment uses a non-default
# subnet (there is no --subnet flag on `grain` yet; it's a Cluster()
# constructor argument today).
CONTROLLER_IP="10.100.0.2"

apt-get update
apt-get install -y --no-install-recommends \
  python3 git openssh-client curl ca-certificates

# --- gce_metadata_server: one static binary, installed (not built from
# source) — see docs/design.md, "GCP credentials", and docs/roadmap.md item
# 4 for how this was verified against a real instance of it. ----------------
curl -fsSL -o /usr/local/bin/gce_metadata_server \
  "https://github.com/salrashid123/gce_metadata_server/releases/download/v${GCE_METADATA_SERVER_VERSION}/gce_metadata_server_${GCE_METADATA_SERVER_VERSION}_linux_amd64"
chmod +x /usr/local/bin/gce_metadata_server

# The system user each gce_metadata_server instance runs as
# (grain/metadata/config.py's `metadata_user` default) — a narrow account
# with no login shell, so a compromised instance is not a compromised shell.
id -u grain-metadata >/dev/null 2>&1 || \
  useradd --system --no-create-home --shell /usr/sbin/nologin grain-metadata

# --- /data: the disk that outlives a controller rebuild (docs/design.md,
# "Secrets on /data"). On GCP this is expected to be a separate persistent
# disk, attached before this script runs; nothing here formats or mounts
# one — the libvirt adapter this repo drives today has no notion of a
# second attached disk per VM, so for a local/dev deployment this is simply
# a directory on the controller's one disk. Fix the adapter, not this
# script, if that gap needs closing. ----------------------------------------
install -d -m0755 /data
install -d -m0711 /data/secrets   # traverse-only by default; see below
install -d -m0700 /data/secrets/github
install -d -m0755 /data/config
install -d -m0755 /data/state
install -d -m0755 /data/state/automation
install -d -m0755 /data/state/git-proxy
install -d -m0755 /data/state/metadata-server
# /data/secrets is 0711 (traverse, not list) rather than 0700 so that
# `grain-metadata` can open /data/secrets/gcp-service-account.json by its
# exact path once an operator places it there — opening a file by absolute
# path only needs execute (search) permission on each ancestor directory,
# never read. When you place that file (docs/runbook.md, first-time setup),
# also run:
#   chown grain-metadata:grain-metadata /data/secrets/gcp-service-account.json
#   chmod 0640 /data/secrets/gcp-service-account.json
# /data/secrets/github stays 0700, root-only: grain-metadata has no business
# reaching GitHub credentials, and the git proxy (which does) runs as root
# today, same as the automation loop — see the systemd units below.

# --- The controller SSH keypair. `dispatch()`/`SshRunner`
# (grain/automation/ssh.py) use the private half to reach sandboxes;
# cloud-init installs the public half as each sandbox's authorized key
# (LibvirtAdapter's `ssh_public_key_path`, grain/adapter/libvirt.py). This
# used to be a manual `ssh-keygen` step (docs/roadmap.md item 3) — generated
# here instead, idempotently, so a re-run of this script (or a boot where
# scripts-user somehow runs twice) never clobbers an existing identity.
#
# The public half does NOT reach the host by anything this script can do —
# the host and the controller are different machines (docs/design.md, "One
# host machine runs everything: a controller VM and a small pool of agent
# sandbox VMs"; admin reaches the controller by SSHing to the host first).
# `LibvirtAdapter.create()`, which needs this file to embed as a sandbox's
# authorized key, runs on the *host*, so the public key still has to be
# carried across that gap by hand once — see docs/runbook.md, "Generate the
# controller SSH keypair", for the exact copy step. It is not a secret, so
# copying it is not a credential-handling concern the way every other file
# under /data/secrets is.
if [ ! -f /data/secrets/controller-ssh ]; then
  ssh-keygen -t ed25519 -f /data/secrets/controller-ssh -N "" -q
fi
chmod 0600 /data/secrets/controller-ssh
chmod 0644 /data/secrets/controller-ssh.pub

# --- Where this repo's code is expected to live once deployed by hand (see
# the top of this script). Owned by root; a `git clone` run as root (e.g.
# over `sudo -i`) lands cleanly here with no extra chown step. -------------
install -d -m0755 /opt/grain

# --- systemd units, installed but not enabled: enabling grain-automation
# before /opt/grain holds real code and /data/secrets/config hold real
# credentials would just fail (or worse, run against nothing). Matches
# docs/runbook.md's previously-hand-written example unit pair — codified
# here instead of left as "write this yourself". Start them once the rest
# of docs/runbook.md's first-time setup checklist is done:
#   systemctl enable --now grain-git-proxy.service
#   systemctl enable --now grain-automation.timer
cat > /etc/systemd/system/grain-automation.service <<'UNIT'
[Unit]
Description=grain automation run-once

[Service]
Type=oneshot
WorkingDirectory=/opt/grain
ExecStart=/usr/bin/python3 -m grain.cli --data-dir /data automation run-once
UNIT

cat > /etc/systemd/system/grain-automation.timer <<'UNIT'
[Unit]
Description=Run grain automation every 2 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=2min

[Install]
WantedBy=timers.target
UNIT

cat > /etc/systemd/system/grain-git-proxy.service <<UNIT
[Unit]
Description=grain git proxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/grain
ExecStart=/usr/bin/python3 -m grain.proxy.server --data-dir /data --host ${CONTROLLER_IP} --port 8080
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload

mkdir -p /etc/grain-tools
cat > /etc/grain-tools/README <<'DOC'
This is a grain controller. It holds every credential in the system
(docs/design.md, "Secrets on /data") — nothing else in the deployment does.

Set up by provision/controller.sh:
- python3, git, openssh-client, ca-certificates
- gce_metadata_server, at /usr/local/bin, and the grain-metadata system user
  it runs each per-sandbox instance as
- the /data/{secrets,config,state} layout grain/automation, grain/proxy and
  grain/metadata already expect
- the controller SSH keypair, /data/secrets/controller-ssh{,.pub}
- /opt/grain, empty, where this repo's code is deployed by hand
- grain-automation.{service,timer} and grain-git-proxy.service, installed
  but not enabled

Still manual, per docs/runbook.md's first-time setup checklist:
- deploying this repo's code to /opt/grain
- every file under /data/secrets/github, /data/secrets/sandbox-tokens.json,
  /data/secrets/gcp-service-account.json (if used), /data/config
- copying /data/secrets/controller-ssh.pub to the host, for
  LibvirtAdapter.ssh_public_key_path to embed into sandboxes it creates
- enabling grain-git-proxy.service and grain-automation.timer
- Claude Code login in each sandbox
DOC
