#!/bin/bash
# Generated by grain — do not edit by hand. See docs/design.md, "The
# controller VM" and "Secrets on /data", and docs/runbook.md's first-time
# setup checklist. Delivered as cloud-init NoCloud user-data, which runs a
# raw shebang script as-is via the scripts-user module — same mechanism
# provision/sandbox.sh uses.
#
# What this script does NOT do, on purpose, matching "no secret is ever
# baked into an image or a provisioning script" (docs/design.md, "Secrets on
# /data"):
#   - it never writes a GitHub token, a GCP service-account key, the repo
#     allowlist, or automation.json — those are placed by hand, once, per
#     docs/runbook.md's first-time setup checklist;
#   - it never deploys this repo's own source onto the box. `grain` has no
#     third-party dependencies (see pyproject.toml — stdlib only), so the
#     only thing missing to invoke `python3 -m grain.cli` is the source tree
#     itself at /opt/grain, and getting it there needs a credential this
#     script has no business holding (this repo's remote is not public).
#     Deploy it by hand, with your own credentials: e.g. `git clone
#     <your-remote> /opt/grain` (the directory is created below, empty, so
#     there's an obvious place to put it).
set -eux

GCE_METADATA_SERVER_VERSION="4.2.5"
# Matches Cluster().controller_ip for the default subnet (10.100.0.0/24) —
# see grain/inventory.py. Edit this if the deployment uses a non-default
# subnet (there is no --subnet flag on `grain` yet; it's a Cluster()
# constructor argument today).
CONTROLLER_IP="10.100.0.2"

apt-get update
apt-get install -y --no-install-recommends \
  python3 git openssh-client curl ca-certificates

# --- gce_metadata_server: one static binary, installed (not built from
# source) — see docs/design.md, "GCP credentials", and docs/roadmap.md item
# 4 for how this was verified against a real instance of it. ----------------
curl -fsSL -o /usr/local/bin/gce_metadata_server \
  "https://github.com/salrashid123/gce_metadata_server/releases/download/v${GCE_METADATA_SERVER_VERSION}/gce_metadata_server_${GCE_METADATA_SERVER_VERSION}_linux_amd64"
chmod +x /usr/local/bin/gce_metadata_server

# The system user each gce_metadata_server instance runs as
# (grain/metadata/config.py's `metadata_user` default) — a narrow account
# with no login shell, so a compromised instance is not a compromised shell.
id -u grain-metadata >/dev/null 2>&1 || \
  useradd --system --no-create-home --shell /usr/sbin/nologin grain-metadata

# The dedicated, unprivileged account `claude -p` (and the MCP server it
# spawns as a child — grain/automation/mcp_server.py) runs as, per dispatch
# (docs/roadmap.md item 8's "Update"). Unlike grain-metadata this one needs
# a real home directory: `claude`'s own installer targets ~/.local/bin, and
# its own OAuth token lives at ~/.claude-oauth-token (placed by
# `configure_claude_token`, grain/automation/configure.py) — a bare `claude
# setup-token` value, deliberately kept separate from any operator's own
# `claude login` session, read into `CLAUDE_CODE_OAUTH_TOKEN` at runtime by
# `dispatch.py`'s own unit script rather than a `~/.claude/.credentials.json`
# file (see `CONTROLLER_AGENT_TOKEN_PATH`'s docstring in dispatch.py for why
# an env var is safe here, unlike when `claude -p` ran on the sandbox).
# Never root, and never the account grain-automation.service itself runs as
# — this is specifically the account that runs untrusted-issue-driven agent
# sessions, and the whole point of moving `claude -p` here from the sandbox
# was to stop giving that session anything worth taking.
id -u grain-agent >/dev/null 2>&1 || \
  useradd --system --create-home --shell /usr/sbin/nologin grain-agent
sudo -u grain-agent bash -c 'curl -fsSL https://claude.ai/install.sh | bash'
# Same PATH fix `provision/sandbox.sh` already needed for the identical
# reason: `systemd-run --uid=grain-agent` is a non-login, non-interactive
# shell that never sources ~/.profile, which is what would otherwise put
# the installer's target directory, ~/.local/bin, on PATH.
ln -sf /home/grain-agent/.local/bin/claude /usr/local/bin/claude

# --- /data: the disk that outlives a controller rebuild (docs/design.md,
# "Secrets on /data"). On GCP this is expected to be a separate persistent
# disk, attached before this script runs; nothing here formats or mounts
# one — the libvirt adapter this repo drives today has no notion of a
# second attached disk per VM, so for a local/dev deployment this is simply
# a directory on the controller's one disk. Fix the adapter, not this
# script, if that gap needs closing. ----------------------------------------
install -d -m0755 /data
install -d -m0711 /data/secrets   # traverse-only by default; see below
install -d -m0700 /data/secrets/github
install -d -m0755 /data/config
install -d -m0755 /data/state
install -d -m0755 /data/state/automation
# One subdirectory per dispatched unit — the controller-local prompt, MCP
# config, and transcript `dispatch.py` now writes for each `claude -p`
# session it starts here (docs/roadmap.md item 8's "Update"). Nothing under
# it is secret (untrusted-but-not-secret prompt content, a path to the SSH
# key rather than the key itself, and the transcript already flowing
# through the audit trail), so 0755 root-owned is fine — same as the parent.
install -d -m0755 /data/state/automation/units
install -d -m0755 /data/state/git-proxy
install -d -m0755 /data/state/metadata-server
# Unlike its two siblings above -- git-proxy and automation, both written
# only by processes that run as root -- this one is written by
# `gce_metadata_server` itself, which `grain/metadata/launcher.py` starts
# as the unprivileged `grain-metadata` user. `-logTarget` is a plain file
# path the binary opens with O_CREAT|O_WRONLY (grain/metadata/config.py's
# docstring), which needs write on the *directory*, not just the file --
# root:root 0755 grants grain-metadata no such thing. Left root-owned like
# its siblings, every instance would fail at startup on its first log
# write, invisibly: `systemd-run` only confirms the unit was submitted,
# never that the process it started kept running, so nothing here would
# surface the failure -- the metadata port would simply never answer.
chown grain-metadata:grain-metadata /data/state/metadata-server
# /data/secrets is 0711 (traverse, not list) rather than 0700 so that
# `grain-metadata` can open /data/secrets/gcp-service-account.json by its
# exact path once an operator places it there — opening a file by absolute
# path only needs execute (search) permission on each ancestor directory,
# never read. When you place that file (docs/runbook.md, first-time setup),
# also run:
#   chown grain-metadata:grain-metadata /data/secrets/gcp-service-account.json
#   chmod 0640 /data/secrets/gcp-service-account.json
# /data/secrets/github stays 0700, root-only: grain-metadata has no business
# reaching GitHub credentials, and the git proxy (which does) runs as root
# today, same as the automation loop — see the systemd units below.

# --- The controller SSH keypair. `dispatch()`/`SshRunner`
# (grain/automation/ssh.py) use the private half to reach sandboxes;
# cloud-init installs the public half as each sandbox's authorized key
# (LibvirtAdapter's `ssh_public_key_path`, grain/adapter/libvirt.py). This
# used to be a manual `ssh-keygen` step (docs/roadmap.md item 3) — generated
# here instead, idempotently, so a re-run of this script (or a boot where
# scripts-user somehow runs twice) never clobbers an existing identity.
#
# The public half does NOT reach the host by anything this script can do —
# the host and the controller are different machines (docs/design.md, "One
# host machine runs everything: a controller VM and a small pool of agent
# sandbox VMs"; admin reaches the controller by SSHing to the host first).
# `LibvirtAdapter.create()`, which needs this file to embed as a sandbox's
# authorized key, runs on the *host*, so the public key still has to be
# carried across that gap by hand once — see docs/runbook.md, "Generate the
# controller SSH keypair", for the exact copy step. It is not a secret, so
# copying it is not a credential-handling concern the way every other file
# under /data/secrets is.
if [ ! -f /data/secrets/controller-ssh ]; then
  ssh-keygen -t ed25519 -f /data/secrets/controller-ssh -N "" -q
fi
chmod 0600 /data/secrets/controller-ssh
chmod 0644 /data/secrets/controller-ssh.pub

# `grain-agent`'s MCP server (grain/automation/mcp_server.py) is a separate
# process from grain-automation.service (still root, unchanged) and needs
# to read this key itself, to build its own SshRunner reaching the sandbox
# it was told to target. Found live: group-readable (chmod 0640, group
# grain-agent) does NOT work for this -- OpenSSH's own client refuses to
# use *any* private key file it considers "too open", which for it means
# anything beyond owner-only 0600/0400, regardless of which group holds
# the read bit or how narrowly that group is scoped. The only thing that
# actually satisfies both processes at once is a second, independent copy,
# each owner-only in its own right. Granting the read grants no
# controller-side privilege either way — the key only ever authenticates
# to a disposable, unprivileged (debian-uid) sandbox account behind the
# existing host firewall, the same reach `grain-agent`'s tools already
# have by design.
install -d -m0700 -o grain-agent -g grain-agent /home/grain-agent/.ssh
install -m0600 -o grain-agent -g grain-agent \
  /data/secrets/controller-ssh /home/grain-agent/.ssh/controller-ssh

# --- Where this repo's code is expected to live once deployed by hand (see
# the top of this script). Owned by root; a `git clone` run as root (e.g.
# over `sudo -i`) lands cleanly here with no extra chown step. -------------
install -d -m0755 /opt/grain

# --- systemd units, installed but not enabled: enabling grain-automation
# before /opt/grain holds real code and /data/secrets/config hold real
# credentials would just fail (or worse, run against nothing). Matches
# docs/runbook.md's previously-hand-written example unit pair — codified
# here instead of left as "write this yourself". Start them once the rest
# of docs/runbook.md's first-time setup checklist is done:
#   systemctl enable --now grain-git-proxy.service
#   systemctl enable --now grain-automation.timer
cat > /etc/systemd/system/grain-automation.service <<'UNIT'
[Unit]
Description=grain automation run-once

[Service]
Type=oneshot
WorkingDirectory=/opt/grain
ExecStart=/usr/bin/python3 -m grain.cli --data-dir /data automation run-once
UNIT

cat > /etc/systemd/system/grain-automation.timer <<'UNIT'
[Unit]
Description=Run grain automation every 1 minute

[Timer]
OnBootSec=1min
OnUnitActiveSec=1min

[Install]
WantedBy=timers.target
UNIT

cat > /etc/systemd/system/grain-git-proxy.service <<UNIT
[Unit]
Description=grain git proxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/grain
ExecStart=/usr/bin/python3 -m grain.proxy.server --data-dir /data --host ${CONTROLLER_IP} --port 8080
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload

mkdir -p /etc/grain-tools
cat > /etc/grain-tools/README <<'DOC'
This is a grain controller. It holds every credential in the system
(docs/design.md, "Secrets on /data") — nothing else in the deployment does.

Set up by provision/controller.sh:
- python3, git, openssh-client, ca-certificates
- gce_metadata_server, at /usr/local/bin, and the grain-metadata system user
  it runs each per-sandbox instance as
- claude (Claude Code CLI), at /usr/local/bin, and the grain-agent system
  user it runs as — `claude -p` runs HERE now, not on the sandboxes
  (docs/roadmap.md item 8's "Update"); grain-agent has its own 0600 copy of
  the controller SSH key at ~/.ssh/controller-ssh (OpenSSH refuses a
  group-readable one, found live) so its MCP server
  (grain/automation/mcp_server.py) can reach the sandbox it was dispatched
  against, and nothing else under /data/secrets
- the /data/{secrets,config,state} layout grain/automation, grain/proxy and
  grain/metadata already expect, including /data/state/automation/units
  where each dispatch's prompt/MCP-config/transcript now live
- the controller SSH keypair, /data/secrets/controller-ssh{,.pub}, plus
  grain-agent's own copy at /home/grain-agent/.ssh/controller-ssh
- /opt/grain, empty, where this repo's code is deployed by hand
- grain-automation.{service,timer} and grain-git-proxy.service, installed
  but not enabled

Still manual, per docs/runbook.md's first-time setup checklist:
- deploying this repo's code to /opt/grain
- every file under /data/secrets/github, /data/secrets/sandbox-tokens.json,
  /data/secrets/gcp-service-account.json (if used), /data/config
- copying /data/secrets/controller-ssh.pub to the host, for
  LibvirtAdapter.ssh_public_key_path to embed into sandboxes it creates
- enabling grain-git-proxy.service and grain-automation.timer
- a Claude Code OAuth token (`claude setup-token`, deliberately separate
  from any operator's own `claude login` session) for grain-agent, placed
  via `configure_claude_token` (grain/automation/configure.py) — one token
  for the whole pool, never one per sandbox, and never touching a sandbox
  at all now
DOC
