#!/bin/bash
# Generated by grain — do not edit by hand. See docs/design.md, "The sandbox
# image" and "Docker and kind". Delivered as cloud-init NoCloud user-data,
# which runs a raw shebang script as-is via the scripts-user module.
set -eux

KIND_VERSION="v0.32.0"
KIND_NODE_IMAGE="kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5"

apt-get update
apt-get install -y --no-install-recommends \
  git curl jq ripgrep fd-find build-essential python3 python3-venv \
  pipx tmux unzip ca-certificates

# Docker, from the official repo — the documented path on Debian, no
# kernel-config question at all.
install -m0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg \
  -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y --no-install-recommends \
  docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# The default cloud-init user ("debian") needs to run docker without sudo.
usermod -aG docker debian

# kind itself.
curl -fsSL -o /usr/local/bin/kind \
  "https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64"
chmod +x /usr/local/bin/kind

# kind's own guidance: common defaults (8192 watches, 128 instances) cannot
# bring up a cluster, and the failures — "too many open files", "failed to
# create fsnotify watcher" — look nothing like their cause.
cat > /etc/sysctl.d/99-grain-kind.conf <<'SYSCTL'
fs.inotify.max_user_watches   = 524288
fs.inotify.max_user_instances = 8192
SYSCTL
sysctl --system

# Pre-load the kind node image into the base: it is on the order of a
# gigabyte, and both recreate and the between-task `docker system prune`
# discard it otherwise.
docker pull "${KIND_NODE_IMAGE}"

mkdir -p /etc/agent-tools
cat > /etc/agent-tools/README <<'DOC'
This sandbox is part of a grain deployment.

- git pushes go through a proxy automatically; GitHub API calls are not
  available from here.
- GCP credentials work through ADC with no setup.
- The sandbox is shared across tasks and cleaned between them, so do not
  leave long-running services behind.
DOC
