#!/bin/bash
# Generated by grain — do not edit by hand. See docs/design.md, "The sandbox
# image" and "Docker and kind". Delivered as cloud-init NoCloud user-data,
# which runs a raw shebang script as-is via the scripts-user module.
set -eux

KIND_VERSION="v0.32.0"
KIND_NODE_IMAGE="kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5"

apt-get update
apt-get install -y --no-install-recommends \
  git curl jq ripgrep fd-find build-essential python3 python3-venv \
  pipx tmux unzip ca-certificates bubblewrap

# Docker, from the official repo — the documented path on Debian, no
# kernel-config question at all.
install -m0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg \
  -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y --no-install-recommends \
  docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# The default cloud-init user ("debian") needs to run docker without sudo.
usermod -aG docker debian

# kind itself.
curl -fsSL -o /usr/local/bin/kind \
  "https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64"
chmod +x /usr/local/bin/kind

# kind's own guidance: common defaults (8192 watches, 128 instances) cannot
# bring up a cluster, and the failures — "too many open files", "failed to
# create fsnotify watcher" — look nothing like their cause.
cat > /etc/sysctl.d/99-grain-kind.conf <<'SYSCTL'
fs.inotify.max_user_watches   = 524288
fs.inotify.max_user_instances = 8192
SYSCTL
sysctl --system

# Pre-load the kind node image into the base: it is on the order of a
# gigabyte, and both recreate and the between-task `docker system prune`
# discard it otherwise.
docker pull "${KIND_NODE_IMAGE}"

# Claude Code runs in-VM with a login credential (see docs/design.md,
# "Alternative agent runtime: Claude Code" and the credential-isolation
# notes below). Two things narrow how far that credential reaches if this
# agent is ever steered into trying to exfiltrate it — both verified live
# on a throwaway test VM before landing here, not just reasoned about:
#
# 1. kernel.yama.ptrace_scope: at the kernel default (0), we read the raw
#    ELF header straight out of an unrelated same-user process's live
#    memory via /proc/<pid>/mem — no special privilege needed, just the
#    same UID. At ptrace_scope=2 the identical attempt fails at open()
#    with "Permission denied". This closes the "read the credential out of
#    the Claude Code process's own memory" path that file-level protection
#    alone does not.
cat > /etc/sysctl.d/99-grain-security.conf <<'SYSCTL'
kernel.yama.ptrace_scope = 2
SYSCTL
sysctl --system

# 2. Claude Code's own `sandbox.credentials.files` (bubblewrap-backed on
#    Linux): a command the agent runs through the sandbox gets `mode:
#    "deny"` on the credential file — verified to come back as a clean
#    ENOENT, not a permission error that would hint something is being
#    hidden, while an ordinary work file bound in alongside it stays fully
#    readable and writable. This is what actually needs `sandbox.enabled`
#    turned on to take effect; the settings below only matter once Claude
#    Code itself is installed and logged in, which is a manual first-setup
#    step, not something this script can do unattended.
sudo -u debian bash -c 'curl -fsSL https://claude.ai/install.sh | bash'
# dispatch.py runs `claude -p` via `systemd-run --uid=debian`, a
# non-login, non-interactive shell that never sources ~/.profile -- and
# ~/.profile is exactly what puts the installer's target directory,
# ~/.local/bin, on PATH. Without this symlink the unit's PATH is just
# systemd's own default (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
# :/sbin:/bin), so a real dispatch fails at "claude: command not found".
# Found live, with a real Claude Code login: every earlier live suite used
# a fake `claude` binary planted straight at /usr/local/bin (already on
# that default PATH), which is why this went uncaught until a real login
# credential existed to test against.
ln -sf /home/debian/.local/bin/claude /usr/local/bin/claude
# `network.allowedDomains` grants the agent's own sandboxed Bash tool
# egress to the git proxy -- without it, `sandbox.enabled: true` (turned on
# for the credential-file deny rule below) also blocks *all* network
# access by default, including the `git push origin ...` dispatch.py's own
# prompt tells the agent to run. Found live, with a real Claude Code login:
# the agent cloned fine (dispatch.py's own `ensure_workspace` clones over
# plain SSH before `claude -p` ever starts, unaffected by this sandbox),
# wrote and committed the requested change, then reported "the sandbox on
# this device blocks connections to 10.100.0.2:8080" and stopped, needing
# a human's sandbox approval it has no way to get non-interactively. Every
# earlier live suite used a fake `claude` binary that never went through
# Claude Code's own sandboxing at all, so this went uncaught until now.
# `10.100.0.2` is `Cluster().controller_ip` -- this script is static
# cloud-init user-data, not templated per-cluster, so it names the same
# default a custom `--cluster-file` subnet would need to override here too.
install -d -o debian -g debian /home/debian/.claude
cat > /home/debian/.claude/settings.json <<'CLAUDESETTINGS'
{
  "sandbox": {
    "enabled": true,
    "network": {
      "allowedDomains": ["10.100.0.2"]
    },
    "credentials": {
      "files": [
        {"path": "~/.claude/.credentials.json", "mode": "deny"}
      ]
    }
  }
}
CLAUDESETTINGS
chown debian:debian /home/debian/.claude/settings.json

mkdir -p /etc/agent-tools
cat > /etc/agent-tools/README <<'DOC'
This sandbox is part of a grain deployment.

- git pushes go through a proxy automatically; GitHub API calls are not
  available from here.
- GCP credentials work through ADC with no setup.
- The sandbox is shared across tasks and cleaned between them, so do not
  leave long-running services behind.
DOC
