#!/bin/bash
# Generated by grain — do not edit by hand. See docs/design.md, "The sandbox
# image" and "Docker and kind". Delivered as cloud-init NoCloud user-data,
# which runs a raw shebang script as-is via the scripts-user module.
set -eux

KIND_VERSION="v0.32.0"
KIND_NODE_IMAGE="kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5"

apt-get update
apt-get install -y --no-install-recommends \
  git curl jq ripgrep fd-find build-essential python3 python3-venv \
  pipx tmux unzip ca-certificates bubblewrap

# Docker, from the official repo — the documented path on Debian, no
# kernel-config question at all.
install -m0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg \
  -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y --no-install-recommends \
  docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# The default cloud-init user ("debian") needs to run docker without sudo.
usermod -aG docker debian

# kind itself.
curl -fsSL -o /usr/local/bin/kind \
  "https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64"
chmod +x /usr/local/bin/kind

# kind's own guidance: common defaults (8192 watches, 128 instances) cannot
# bring up a cluster, and the failures — "too many open files", "failed to
# create fsnotify watcher" — look nothing like their cause.
cat > /etc/sysctl.d/99-grain-kind.conf <<'SYSCTL'
fs.inotify.max_user_watches   = 524288
fs.inotify.max_user_instances = 8192
SYSCTL
sysctl --system

# Pre-load the kind node image into the base: it is on the order of a
# gigabyte, and both recreate and the between-task `docker system prune`
# discard it otherwise.
docker pull "${KIND_NODE_IMAGE}"

# Claude Code no longer runs on the sandbox at all (docs/roadmap.md item
# 8's "Update"). It used to, with a real login credential here, and this
# script used to carry a substantial section hardening that: kernel.yama.
# ptrace_scope=2 against reading the credential out of the process's own
# memory, and Claude Code's own `sandbox.credentials.files: deny` against
# reading it as a file. Both were real, verified-live protections against
# a real problem -- but neither one could close the actual hole a full
# live-debugging session found: the credential leaks into any unsandboxed
# Bash subprocess's environment trivially (confirmed live via a plain
# `env`), and the agent readily discovers `dangerouslyDisableSandbox: true`
# on its own to get there. Environment variables aren't files or process
# memory -- no amount of sandbox tuning here could ever have closed that
# gap. The actual fix: `claude -p` now runs on the controller instead (see
# `provision/controller.sh`), with its entire native tool roster disabled
# and replaced by narrow MCP tools (`grain/automation/mcp_server.py`) that
# reach this sandbox over SSH for everything it actually needs to do. The
# sandbox goes back to holding nothing worth protecting -- the host
# firewall and the git-proxy's per-sandbox token scoping (both unrelated to
# this change) are its only real boundary now, same as they always were for
# everything except the one thing that used to live here.

mkdir -p /etc/agent-tools
cat > /etc/agent-tools/README <<'DOC'
This sandbox is part of a grain deployment.

- git pushes go through a proxy automatically; GitHub API calls are not
  available from here.
- GCP credentials work through ADC with no setup.
- The sandbox is shared across tasks and cleaned between them, so do not
  leave long-running services behind.
DOC
