"""libvirt-backed VM lifecycle.

Lima's `networks: - lima: <name>` stanza — the mechanism `lima.py` was built
around — turned out to be macOS-only: Lima 2.2.0 rejects it outright on
Linux ("field `networks[0].lima` is only supported on macOS right now"),
verified empirically on this host. That answers open question 1 in
docs/design.md. This module is the libvirt driver the design named as the
fallback: same `HostAdapter` interface, same inventory-assigned addresses,
same pre-existing `br-grain` bridge built by `net_linux.py` — only the driver
underneath changes.

Two differences from the Lima driver, both consequences of not having Lima's
guest agent:

- **No automatic image download.** `VmSpec.image` must be a local path to a
  qcow2 base image; the operator fetches it once, the same way the design
  already expected a "version-controlled provisioning script" rather than an
  auto-pulled image for the sandbox base.
- **The static address is delivered by cloud-init, not a guest agent.** A
  NoCloud seed (meta-data + a network-config pinning the assigned address)
  is what makes "addresses assigned, never discovered" concretely true here.
  The seed is matched to the guest NIC by MAC address, deterministically
  derived from the assigned IP, so it does not depend on predictable
  interface naming inside the guest.

Attaching straight to `br-grain` by name needs no libvirt-managed network
object at all — one less layer than Lima's own network abstraction required.
"""

from __future__ import annotations

import ipaddress
from collections.abc import Sequence
from pathlib import Path

from ..inventory import Cluster, Role, VmSpec
from ..run import Runner
from .base import HostAdapter, Network, VmInfo, VmState

LIBVIRT_URI = "qemu:///system"
# Explicit, not ambient: a plain `virsh` with no `-c` connects to
# `qemu:///session` for a non-root caller — a separate, unprivileged
# libvirtd instance whose networking can't attach to a host bridge like
# `br-grain` at all. Verified live: `virsh uri` as an ordinary user in the
# `libvirt` group prints `qemu:///session`, not `qemu:///system`, even
# though that same user can reach the system instance directly (no `sudo`
# needed) once told to.

_STATE_MAP = {
    "running": VmState.RUNNING,
    "shut off": VmState.STOPPED,
    "idle": VmState.RUNNING,
    "paused": VmState.STOPPED,
}


def mac_for(address: ipaddress.IPv4Address) -> str:
    """A deterministic, locally-administered MAC for one assigned address.

    Derived from the address itself so the seed's network-config can match
    the guest NIC by MAC rather than by a guessed interface name — which
    varies with the guest's udev rules and the emulated chipset.
    """
    octets = address.packed[-3:]
    return "52:54:00:" + ":".join(f"{b:02x}" for b in octets)


def render_domain_xml(cluster: Cluster, spec: VmSpec, disk_path: Path,
                       seed_path: Path) -> str:
    """Render the libvirt domain XML for one VM. Pure; no side effects.

    Written as an f-string rather than via a library, for the same reason
    `lima.py` rendered YAML by hand: the adapter has no dependencies beyond
    the standard library.
    """
    address = cluster.address_of(spec.name)
    iface = cluster.interface_of(spec.name)
    mac = mac_for(address)
    return f"""<!-- Generated by grain — do not edit by hand. -->
<domain type='kvm'>
  <name>{spec.name}</name>
  <memory unit='MiB'>{spec.mem_mb}</memory>
  <vcpu>{spec.cpus}</vcpu>
  <os>
    <type arch='x86_64' machine='q35'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-passthrough'/>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='{disk_path}'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <!-- The NoCloud seed, attached over virtio rather than as a SATA/IDE
           cdrom: Debian's cloud kernel flavor has no AHCI/ATA driver at
           all, so a bus='sata' cdrom is never enumerated and ds-identify
           finds nothing — verified on this host, see docs/host-adapter.md. -->
      <driver name='qemu' type='raw'/>
      <source file='{seed_path}'/>
      <target dev='vdb' bus='virtio'/>
      <readonly/>
    </disk>
    <interface type='bridge'>
      <source bridge='{cluster.bridge}'/>
      <target dev='{iface}'/>
      <mac address='{mac}'/>
      <model type='virtio'/>
    </interface>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
  </devices>
</domain>
"""


def render_meta_data(name: str, ssh_public_keys: Sequence[str] = ()) -> str:
    """cloud-init NoCloud meta-data.

    `public-keys` is honoured independent of the user-data format, so this
    is the one place to hand the default user an authorized key even though
    `render_user_data` repurposes user-data as a raw provisioning script
    rather than a `#cloud-config`. Without it, nothing outside the guest
    console can reach a VM — see docs/design.md, "Admin entry"; this is what
    gives both a human admin and the controller (for the automation dispatch
    loop) a way in.

    Takes a *sequence* of keys, not one (docs/bootstrap.md Phase 1): cloud-init
    accepts one `public-keys` entry per key, which is what lets a VM carry
    two independently-purposed keys at once — an admin key (controller and
    every sandbox, for setup/repair/debugging) and the controller's own key
    (sandboxes only, for automation dispatch) — see `LibvirtAdapter.create`.
    Blank/falsy entries are skipped, so callers can pass a fixed two-item
    list built from possibly-absent files without filtering it themselves.
    """
    meta = f"instance-id: {name}\nlocal-hostname: {name}\n"
    keys = [k.strip() for k in ssh_public_keys if k and k.strip()]
    if keys:
        meta += "public-keys:\n" + "".join(f"  - {k}\n" for k in keys)
    return meta


def render_user_data(provision_script: str | None) -> str:
    """A raw shebang script is a valid NoCloud user-data payload as-is —
    cloud-init's scripts-user module runs it directly at first boot, the
    same shape `docs/design.md` already used for the Lima provisioning
    stanza. With nothing to run, an empty cloud-config is still a valid
    NoCloud user-data file.
    """
    if provision_script:
        return provision_script
    return "#cloud-config\n{}\n"


def render_network_config(cluster: Cluster, spec: VmSpec) -> str:
    """cloud-init network-config v2, pinning the inventory-assigned address.

    Matched by MAC rather than interface name — see `mac_for`.
    """
    address = cluster.address_of(spec.name)
    mac = mac_for(address)
    return (
        "network:\n"
        "  version: 2\n"
        "  ethernets:\n"
        "    eth0:\n"
        f"      match:\n"
        f"        macaddress: '{mac}'\n"
        "      set-name: eth0\n"
        f"      addresses: [{address}/{cluster.subnet.prefixlen}]\n"
        f"      gateway4: {cluster.host_ip}\n"
        "      nameservers:\n"
        "        addresses: [8.8.8.8, 1.1.1.1]\n"
    )


class LibvirtAdapter(HostAdapter):
    def __init__(self, cluster: Cluster, runner: Runner, network: Network,
                 config_dir: Path | None = None,
                 admin_public_key_path: Path | None = None,
                 controller_public_key_path: Path | None = None,
                 apparmor_rules_path: Path | None = None) -> None:
        super().__init__(cluster, network)
        self.runner = runner
        self.config_dir = config_dir or Path("/var/lib/grain/instances")
        # Debian's libvirt-daemon-system ships an AppArmor profile for qemu
        # that only allows the default /var/lib/libvirt/images/ path (plus
        # a couple of others) -- found live: a VM whose disk lived at
        # config_dir's own default, a custom path, failed to start with
        # "Cannot access storage file ... Permission denied", not an
        # ownership problem (dynamic_ownership had already corrected that)
        # but AppArmor denying the open() before permissions are even
        # checked. This is the extension point Debian/Ubuntu ship
        # specifically so a package upgrade doesn't clobber admin-added
        # rules. Injectable for the same reason config_dir/the key paths
        # are: a test points it at a tmp_path instead of a real system file.
        self.apparmor_rules_path = (
            apparmor_rules_path
            or Path("/etc/apparmor.d/local/abstractions/libvirt-qemu")
        )
        # Both host-local, deliberately not /data/secrets/... — /data lives
        # on the *controller* VM, and this adapter runs on the *host*, a
        # different machine (docs/design.md, "One host machine runs
        # everything"). Mirrors `config_dir`'s own host-local default one
        # directory up. Two keys, two roles (docs/bootstrap.md Phase 1 — the
        # bug this replaces: one key path fed to every VM, which left the
        # controller with no authorized key at all until an operator's own
        # key was pasted in and then overwritten):
        #
        #   admin       -> controller AND every sandbox. For setup, repair,
        #                  and admin debugging access — see docs/design.md,
        #                  "Admin entry". Not a secret at this path; only
        #                  the *public* half ever lives here.
        #   controller  -> sandboxes only. The automation dispatch path;
        #                  the controller generates this keypair itself on
        #                  first boot (provision/controller.sh) and this is
        #                  only ever the *public* half, read back by
        #                  `grain host bootstrap` once the controller is up
        #                  (docs/runbook.md's old "copy the pubkey to the
        #                  host" step, now scripted).
        self.admin_public_key_path = (
            admin_public_key_path or Path("/var/lib/grain/admin-ssh.pub")
        )
        self.controller_public_key_path = (
            controller_public_key_path or Path("/var/lib/grain/controller-ssh.pub")
        )

    def _ensure_apparmor_allows(self, *dirs: Path) -> None:
        """No-op if AppArmor's local-abstractions directory doesn't exist at
        all -- not every host runs AppArmor. Idempotent otherwise: skips
        whichever of `dirs` is already allowlisted, so a normal three-VM
        bootstrap (controller, two sandboxes) does at most one real write.
        """
        if not self.apparmor_rules_path.parent.is_dir():
            return
        existing = (
            self.apparmor_rules_path.read_text()
            if self.apparmor_rules_path.exists() else ""
        )
        missing = [d for d in dirs if str(d) not in existing]
        if not missing:
            return
        addition = "".join(f"  {d}/*.qcow2 rwk,\n  {d}/*.iso rk,\n" for d in missing)
        self.runner.run(["tee", "-a", str(self.apparmor_rules_path)],
                         stdin=addition, check=True)
        self.runner.run(["systemctl", "reload", "apparmor"], check=False)

    # --- lifecycle --------------------------------------------------------
    def create(self, spec: VmSpec, provision_script: str | None = None) -> None:
        if self.state(spec.name) is not VmState.ABSENT:
            raise RuntimeError(
                f"{spec.name} already exists; use recreate() to replace it"
            )
        # spec.image is normally a real absolute path (the README: "name
        # the real path... via --image or cluster.toml"), but Cluster's own
        # bare-string default ("debian-12") resolves to a meaningless "."
        # -- not worth allowlisting, and AppArmor rules are absolute paths
        # anyway.
        image_dir = Path(spec.image).parent
        dirs = (self.config_dir, image_dir) if image_dir.is_absolute() else (self.config_dir,)
        self._ensure_apparmor_allows(*dirs)
        self.config_dir.mkdir(parents=True, exist_ok=True)

        disk_path = self.config_dir / f"{spec.name}.qcow2"
        self.runner.run(
            ["qemu-img", "create", "-f", "qcow2", "-F", "qcow2",
             "-b", spec.image, str(disk_path), f"{spec.disk_gb}G"]
        )

        meta_data_path = self.config_dir / f"{spec.name}-meta-data"
        user_data_path = self.config_dir / f"{spec.name}-user-data"
        network_config_path = self.config_dir / f"{spec.name}-network-config"
        admin_key = (
            self.admin_public_key_path.read_text()
            if self.admin_public_key_path.exists() else ""
        )
        controller_key = (
            self.controller_public_key_path.read_text()
            if self.controller_public_key_path.exists() else ""
        )
        # Role -> keys: the controller trusts only the admin key (it has no
        # automation dispatch path pointed at itself); a sandbox trusts both
        # — the admin key for direct debugging access, the controller key
        # for automation dispatch. See __init__'s docstring.
        keys = [admin_key] if spec.role is Role.CONTROLLER else [admin_key, controller_key]
        meta_data_path.write_text(render_meta_data(spec.name, keys))
        user_data_path.write_text(render_user_data(provision_script))
        network_config_path.write_text(render_network_config(self.cluster, spec))

        seed_path = self.config_dir / f"{spec.name}-seed.iso"
        self.runner.run(
            ["cloud-localds", f"--network-config={network_config_path}",
             str(seed_path), str(user_data_path), str(meta_data_path)]
        )

        xml_path = self.config_dir / f"{spec.name}.xml"
        xml_path.write_text(render_domain_xml(self.cluster, spec, disk_path, seed_path))
        self.runner.run(["virsh", "-c", LIBVIRT_URI, "define", str(xml_path)])

    def start(self, name: str) -> None:
        self.runner.run(["virsh", "-c", LIBVIRT_URI, "start", name])

    def stop(self, name: str) -> None:
        if self.state(name) is VmState.RUNNING:
            self.runner.run(["virsh", "-c", LIBVIRT_URI, "shutdown", name])

    def destroy(self, name: str) -> None:
        if self.state(name) is VmState.ABSENT:
            return
        self.runner.run(["virsh", "-c", LIBVIRT_URI, "destroy", name], check=False)
        # --remove-all-storage only works for storage-pool-managed volumes;
        # these are plain files, so libvirt refuses to touch them and we
        # remove them ourselves (verified: it leaves them behind otherwise).
        self.runner.run(["virsh", "-c", LIBVIRT_URI, "undefine", name, "--nvram"], check=False)
        for suffix in (".qcow2", "-seed.iso", "-meta-data", "-user-data",
                       "-network-config", ".xml"):
            (self.config_dir / f"{name}{suffix}").unlink(missing_ok=True)

    def state(self, name: str) -> VmState:
        for info in self.list_vms():
            if info.name == name:
                return info.state
        return VmState.ABSENT

    def list_vms(self) -> list[VmInfo]:
        result = self.runner.run(["virsh", "-c", LIBVIRT_URI, "list", "--all"], check=False)
        if result.returncode != 0:
            return []
        infos: list[VmInfo] = []
        for line in result.stdout.splitlines():
            line = line.strip()
            if not line or line.startswith("Id ") or set(line) <= {"-", " "}:
                continue
            fields = line.split(None, 2)
            if len(fields) < 2:
                continue
            _id, name, *rest = fields
            if name not in self.cluster.names:
                continue  # not ours; leave other libvirt domains alone
            state_text = rest[0] if rest else ""
            infos.append(
                VmInfo(
                    name=name,
                    state=_STATE_MAP.get(state_text, VmState.UNKNOWN),
                    address=self.cluster.address_of(name),
                )
            )
        return infos
