"""libvirt-backed VM lifecycle.

Lima's `networks: - lima: <name>` stanza — the mechanism `lima.py` was built
around — turned out to be macOS-only: Lima 2.2.0 rejects it outright on
Linux ("field `networks[0].lima` is only supported on macOS right now"),
verified empirically on this host. That answers open question 1 in
docs/design.md. This module is the libvirt driver the design named as the
fallback: same `HostAdapter` interface, same inventory-assigned addresses,
same pre-existing `br-grain` bridge built by `net_linux.py` — only the driver
underneath changes.

Two differences from the Lima driver, both consequences of not having Lima's
guest agent:

- **No automatic image download.** `VmSpec.image` must be a local path to a
  qcow2 base image; the operator fetches it once, the same way the design
  already expected a "version-controlled provisioning script" rather than an
  auto-pulled image for the sandbox base.
- **The static address is delivered by cloud-init, not a guest agent.** A
  NoCloud seed (meta-data + a network-config pinning the assigned address)
  is what makes "addresses assigned, never discovered" concretely true here.
  The seed is matched to the guest NIC by MAC address, deterministically
  derived from the assigned IP, so it does not depend on predictable
  interface naming inside the guest.

Attaching straight to `br-grain` by name needs no libvirt-managed network
object at all — one less layer than Lima's own network abstraction required.
"""

from __future__ import annotations

import ipaddress
from pathlib import Path

from ..inventory import Cluster, VmSpec
from ..run import Runner
from .base import HostAdapter, Network, VmInfo, VmState

_STATE_MAP = {
    "running": VmState.RUNNING,
    "shut off": VmState.STOPPED,
    "idle": VmState.RUNNING,
    "paused": VmState.STOPPED,
}


def mac_for(address: ipaddress.IPv4Address) -> str:
    """A deterministic, locally-administered MAC for one assigned address.

    Derived from the address itself so the seed's network-config can match
    the guest NIC by MAC rather than by a guessed interface name — which
    varies with the guest's udev rules and the emulated chipset.
    """
    octets = address.packed[-3:]
    return "52:54:00:" + ":".join(f"{b:02x}" for b in octets)


def render_domain_xml(cluster: Cluster, spec: VmSpec, disk_path: Path,
                       seed_path: Path) -> str:
    """Render the libvirt domain XML for one VM. Pure; no side effects.

    Written as an f-string rather than via a library, for the same reason
    `lima.py` rendered YAML by hand: the adapter has no dependencies beyond
    the standard library.
    """
    address = cluster.address_of(spec.name)
    iface = cluster.interface_of(spec.name)
    mac = mac_for(address)
    return f"""<!-- Generated by grain — do not edit by hand. -->
<domain type='kvm'>
  <name>{spec.name}</name>
  <memory unit='MiB'>{spec.mem_mb}</memory>
  <vcpu>{spec.cpus}</vcpu>
  <os>
    <type arch='x86_64' machine='q35'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-passthrough'/>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='{disk_path}'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <!-- The NoCloud seed, attached over virtio rather than as a SATA/IDE
           cdrom: Debian's cloud kernel flavor has no AHCI/ATA driver at
           all, so a bus='sata' cdrom is never enumerated and ds-identify
           finds nothing — verified on this host, see docs/host-adapter.md. -->
      <driver name='qemu' type='raw'/>
      <source file='{seed_path}'/>
      <target dev='vdb' bus='virtio'/>
      <readonly/>
    </disk>
    <interface type='bridge'>
      <source bridge='{cluster.bridge}'/>
      <target dev='{iface}'/>
      <mac address='{mac}'/>
      <model type='virtio'/>
    </interface>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
  </devices>
</domain>
"""


def render_meta_data(name: str) -> str:
    return f"instance-id: {name}\nlocal-hostname: {name}\n"


def render_user_data(provision_script: str | None) -> str:
    """A raw shebang script is a valid NoCloud user-data payload as-is —
    cloud-init's scripts-user module runs it directly at first boot, the
    same shape `docs/design.md` already used for the Lima provisioning
    stanza. With nothing to run, an empty cloud-config is still a valid
    NoCloud user-data file.
    """
    if provision_script:
        return provision_script
    return "#cloud-config\n{}\n"


def render_network_config(cluster: Cluster, spec: VmSpec) -> str:
    """cloud-init network-config v2, pinning the inventory-assigned address.

    Matched by MAC rather than interface name — see `mac_for`.
    """
    address = cluster.address_of(spec.name)
    mac = mac_for(address)
    return (
        "network:\n"
        "  version: 2\n"
        "  ethernets:\n"
        "    eth0:\n"
        f"      match:\n"
        f"        macaddress: '{mac}'\n"
        "      set-name: eth0\n"
        f"      addresses: [{address}/{cluster.subnet.prefixlen}]\n"
        f"      gateway4: {cluster.host_ip}\n"
    )


class LibvirtAdapter(HostAdapter):
    def __init__(self, cluster: Cluster, runner: Runner, network: Network,
                 config_dir: Path | None = None) -> None:
        super().__init__(cluster, network)
        self.runner = runner
        self.config_dir = config_dir or Path("/var/lib/grain/instances")

    # --- lifecycle --------------------------------------------------------
    def create(self, spec: VmSpec, provision_script: str | None = None) -> None:
        if self.state(spec.name) is not VmState.ABSENT:
            raise RuntimeError(
                f"{spec.name} already exists; use recreate() to replace it"
            )
        self.config_dir.mkdir(parents=True, exist_ok=True)

        disk_path = self.config_dir / f"{spec.name}.qcow2"
        self.runner.run(
            ["qemu-img", "create", "-f", "qcow2", "-F", "qcow2",
             "-b", spec.image, str(disk_path), f"{spec.disk_gb}G"]
        )

        meta_data_path = self.config_dir / f"{spec.name}-meta-data"
        user_data_path = self.config_dir / f"{spec.name}-user-data"
        network_config_path = self.config_dir / f"{spec.name}-network-config"
        meta_data_path.write_text(render_meta_data(spec.name))
        user_data_path.write_text(render_user_data(provision_script))
        network_config_path.write_text(render_network_config(self.cluster, spec))

        seed_path = self.config_dir / f"{spec.name}-seed.iso"
        self.runner.run(
            ["cloud-localds", f"--network-config={network_config_path}",
             str(seed_path), str(user_data_path), str(meta_data_path)]
        )

        xml_path = self.config_dir / f"{spec.name}.xml"
        xml_path.write_text(render_domain_xml(self.cluster, spec, disk_path, seed_path))
        self.runner.run(["virsh", "define", str(xml_path)])

    def start(self, name: str) -> None:
        self.runner.run(["virsh", "start", name])

    def stop(self, name: str) -> None:
        if self.state(name) is VmState.RUNNING:
            self.runner.run(["virsh", "shutdown", name])

    def destroy(self, name: str) -> None:
        if self.state(name) is VmState.ABSENT:
            return
        self.runner.run(["virsh", "destroy", name], check=False)
        # --remove-all-storage only works for storage-pool-managed volumes;
        # these are plain files, so libvirt refuses to touch them and we
        # remove them ourselves (verified: it leaves them behind otherwise).
        self.runner.run(["virsh", "undefine", name, "--nvram"], check=False)
        for suffix in (".qcow2", "-seed.iso", "-meta-data", "-user-data",
                       "-network-config", ".xml"):
            (self.config_dir / f"{name}{suffix}").unlink(missing_ok=True)

    def state(self, name: str) -> VmState:
        for info in self.list_vms():
            if info.name == name:
                return info.state
        return VmState.ABSENT

    def list_vms(self) -> list[VmInfo]:
        result = self.runner.run(["virsh", "list", "--all"], check=False)
        if result.returncode != 0:
            return []
        infos: list[VmInfo] = []
        for line in result.stdout.splitlines():
            line = line.strip()
            if not line or line.startswith("Id ") or set(line) <= {"-", " "}:
                continue
            fields = line.split(None, 2)
            if len(fields) < 2:
                continue
            _id, name, *rest = fields
            if name not in self.cluster.names:
                continue  # not ours; leave other libvirt domains alone
            state_text = rest[0] if rest else ""
            infos.append(
                VmInfo(
                    name=name,
                    state=_STATE_MAP.get(state_text, VmState.UNKNOWN),
                    address=self.cluster.address_of(name),
                )
            )
        return infos
