"""Lima-backed VM lifecycle.

Lima runs on both Linux and macOS, which is why the design prefers it: if it
holds up on Linux, the same driver, templates and provisioning scripts serve
both hosts and a port costs only the networking. That is open question 1 in
docs/design.md, and it is the first thing step 2 of the plan should settle.

If Lima disappoints on Linux, the fallback is a libvirt driver implementing
the same `HostAdapter` interface. That costs a second driver, not a
redesign — which is the entire point of having the interface.

Note what this class does *not* do: it never reports a VM's address. Those
are assigned by the inventory, so `address()` stays pure and the firewall
rules cannot disagree with the VMs about who is who.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..inventory import Cluster, VmSpec
from ..run import Runner
from .base import HostAdapter, Network, VmInfo, VmState

# Lima's own status strings, mapped onto ours.
_STATE_MAP = {
    "Running": VmState.RUNNING,
    "Stopped": VmState.STOPPED,
    "Broken": VmState.UNKNOWN,
}


def render_instance_config(cluster: Cluster, spec: VmSpec,
                           provision_script: str | None = None) -> str:
    """Render the Lima instance YAML for one VM.

    Written as text rather than via a YAML library so the adapter has no
    dependencies beyond the standard library — it has to run on a stock
    Debian host before anything else is installed.
    """
    address = cluster.address_of(spec.name)
    lines = [
        "# Generated by grain — do not edit by hand.",
        f"# {spec.role.value} {spec.name} at {address}",
        "images:",
        f"- location: {spec.image}",
        f"cpus: {spec.cpus}",
        f'memory: "{spec.mem_mb}MiB"',
        f'disk: "{spec.disk_gb}GiB"',
        "",
        "# Addresses are assigned by the inventory, never by DHCP discovery:",
        "# the firewall's anti-spoofing rules and the VM must agree exactly.",
        "#",
        "# UNVERIFIED: this stanza is the crux of open question 1 in the",
        "# design — whether Lima can attach a guest to a host bridge with a",
        "# fixed address, on Linux. Confirm against the pinned Lima version",
        "# before building anything on top; if it cannot, this is the point",
        "# where a libvirt driver replaces the file, not the interface.",
        "networks:",
        "- lima: grain",
        f"  interface: {cluster.interface_of(spec.name)}",
        "",
        "mountType: virtiofs",
        "mounts: []",
        "",
    ]
    if provision_script:
        lines += [
            "provision:",
            "- mode: system",
            "  script: |",
            *[f"    {line}" for line in provision_script.splitlines()],
            "",
        ]
    return "\n".join(lines)


class LimaAdapter(HostAdapter):
    def __init__(self, cluster: Cluster, runner: Runner, network: Network,
                 config_dir: Path | None = None) -> None:
        super().__init__(cluster, network)
        self.runner = runner
        self.config_dir = config_dir or Path("/var/lib/grain/instances")

    # --- lifecycle --------------------------------------------------------
    def create(self, spec: VmSpec, provision_script: str | None = None) -> None:
        if self.state(spec.name) is not VmState.ABSENT:
            raise RuntimeError(
                f"{spec.name} already exists; use recreate() to replace it"
            )
        config = render_instance_config(self.cluster, spec, provision_script)
        path = self.config_dir / f"{spec.name}.yaml"
        self.config_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(config)
        self.runner.run(
            ["limactl", "create", f"--name={spec.name}", "--tty=false", str(path)]
        )

    def start(self, name: str) -> None:
        self.runner.run(["limactl", "start", "--tty=false", name])

    def stop(self, name: str) -> None:
        if self.state(name) is VmState.RUNNING:
            self.runner.run(["limactl", "stop", name])

    def destroy(self, name: str) -> None:
        if self.state(name) is VmState.ABSENT:
            return
        self.runner.run(["limactl", "delete", "--force", name])

    def state(self, name: str) -> VmState:
        for info in self.list_vms():
            if info.name == name:
                return info.state
        return VmState.ABSENT

    def list_vms(self) -> list[VmInfo]:
        result = self.runner.run(["limactl", "list", "--json"], check=False)
        if result.returncode != 0:
            return []
        infos: list[VmInfo] = []
        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            entry = json.loads(line)
            name = entry.get("name")
            if name not in self.cluster.names:
                continue  # not ours; leave other Lima instances alone
            infos.append(
                VmInfo(
                    name=name,
                    state=_STATE_MAP.get(entry.get("status", ""), VmState.UNKNOWN),
                    address=self.cluster.address_of(name),
                )
            )
        return infos
