"""Linux private network and filtering policy.

The security model of the whole system rests on this file. The design is
explicit that a silently-permissive rule is the failure that invalidates
everything else, so the ruleset is produced by a pure function that can be
inspected and tested without root, a hypervisor, or a running kernel.

Policy, in the order the rules must be evaluated:

1.  Established traffic is accepted, so replies do not need their own rules.
2.  **Anti-spoofing.** Each VM's tap accepts only that VM's assigned source
    address. This is what makes the source address a fact rather than a
    claim, and it is why the design keeps addresses and rules derived from
    one inventory.
3.  Controller may reach any sandbox — it drives the agent servers.
4.  A sandbox may reach the controller on exactly two ports: the git proxy,
    and *its own* metadata server instance. Not another sandbox's.
5.  Everything else inside the subnet is dropped, which is what stops
    sandbox-to-sandbox traffic.
6.  Egress leaves the subnet only under the open policy.

Traffic to the metadata anycast address is DNAT'd per source sandbox, so
each sandbox reaches a different metadata instance at the same well-known
address. That is what makes "authenticated by network position" true per-VM
without any client configuration — the property tokens cannot provide,
because Google's client libraries will not send a custom header.

Note the host's own INPUT chain is deliberately *not* managed here. On a
cloud host the provider firewall is the inbound control, and a generated
INPUT policy is an excellent way to lock yourself out of a machine whose
console you may not have. `render_host_input_rules` produces one for hosts
that need it, but nothing applies it automatically.
"""

from __future__ import annotations

from ..inventory import (
    METADATA_ANYCAST,
    METADATA_PORT,
    GIT_PROXY_PORT,
    Cluster,
)
from ..run import Runner
from .base import EgressMode

TABLE = "grain"
NAT_TABLE = "grain_nat"


def render_ruleset(cluster: Cluster, egress: EgressMode) -> str:
    """Produce the complete nftables ruleset. Pure; no side effects."""
    lines: list[str] = []
    add = lines.append

    add("# Generated by grain — do not edit by hand.")
    add(f"# {cluster.sandbox_count} sandbox(es) on {cluster.subnet}, egress={egress.value}")
    add(f"delete table inet {TABLE}")
    add(f"delete table ip {NAT_TABLE}")
    add(f"table inet {TABLE} {{")
    add("  chain forward {")
    add("    type filter hook forward priority filter; policy drop;")
    add("")
    add("    # 1. established")
    add("    ct state established,related accept")
    add("")
    add("    # 2. anti-spoofing: a tap may only source its own address")
    for name in cluster.names:
        iface = cluster.interface_of(name)
        addr = cluster.address_of(name)
        add(f'    iifname "{iface}" ip saddr != {addr} drop')
    add("")
    add("    # 3. controller drives the sandboxes")
    add(f"    ip saddr {cluster.controller_ip} ip daddr {cluster.subnet} accept")
    add("")
    add("    # 4. each sandbox reaches the git proxy and its own metadata server")
    for name in cluster.sandbox_names:
        addr = cluster.address_of(name)
        add(
            f"    ip saddr {addr} ip daddr {cluster.controller_ip} "
            f"tcp dport {GIT_PROXY_PORT} accept"
        )
        add(
            f"    ip saddr {addr} ip daddr {cluster.controller_ip} "
            f"tcp dport {cluster.metadata_port(name)} accept"
        )
    add("")
    add("    # 5. anything else inside the subnet, including sandbox-to-sandbox")
    add(f"    ip saddr {cluster.subnet} ip daddr {cluster.subnet} drop")
    add("")
    add("    # 6. egress")
    if egress is EgressMode.OPEN:
        add(f'    ip saddr {cluster.subnet} oifname != "{cluster.bridge}" accept')
    else:
        add("    # allowlist mode: no direct egress; reach the world via a proxy")
    add("  }")
    add("}")
    add("")
    add(f"table ip {NAT_TABLE} {{")
    add("  chain prerouting {")
    add("    type nat hook prerouting priority dstnat; policy accept;")
    add("    # each sandbox's metadata lookups go to its own instance")
    for name in cluster.sandbox_names:
        addr = cluster.address_of(name)
        add(
            f"    ip saddr {addr} ip daddr {METADATA_ANYCAST} "
            f"tcp dport {METADATA_PORT} dnat to "
            f"{cluster.controller_ip}:{cluster.metadata_port(name)}"
        )
    add("  }")
    add("  chain postrouting {")
    add("    type nat hook postrouting priority srcnat; policy accept;")
    if egress is EgressMode.OPEN:
        add(f'    ip saddr {cluster.subnet} oifname != "{cluster.bridge}" masquerade')
    add("  }")
    add("}")
    return "\n".join(lines) + "\n"


def render_host_input_rules(cluster: Cluster, ssh_port: int = 22) -> str:
    """An INPUT policy for hosts without a provider firewall.

    Not applied automatically, and not called by `network_up`. Generating a
    default-drop INPUT chain on a remote machine is how people lose access to
    remote machines; adopt this deliberately, with console access to hand.
    """
    return "\n".join(
        [
            "# Generated by grain — review before applying.",
            "table inet grain_input {",
            "  chain input {",
            "    type filter hook input priority filter; policy drop;",
            "    ct state established,related accept",
            '    iifname "lo" accept',
            f"    tcp dport {ssh_port} accept",
            f'    iifname "{cluster.bridge}" ip saddr {cluster.subnet} accept',
            "  }",
            "}",
            "",
        ]
    )


class LinuxNetwork:
    """Creates the bridge and applies the ruleset."""

    def __init__(self, cluster: Cluster, runner: Runner) -> None:
        self.cluster = cluster
        self.runner = runner

    def up(self, egress: EgressMode = EgressMode.OPEN) -> None:
        self._ensure_bridge()
        self._enable_forwarding()
        self.apply_rules(egress)

    def apply_rules(self, egress: EgressMode) -> None:
        ruleset = render_ruleset(self.cluster, egress)
        # `delete table` on a table that does not exist is an error, so the
        # generated ruleset is applied with -f and failures tolerated on the
        # first run only if the tables are genuinely absent. Creating them
        # first makes the delete unconditional and the whole apply atomic.
        self._ensure_tables_exist()
        self.runner.run(["nft", "-f", "-"], stdin=ruleset)

    def _ensure_tables_exist(self) -> None:
        for family, table in (("inet", TABLE), ("ip", NAT_TABLE)):
            self.runner.run(["nft", "add", "table", family, table], check=False)

    def _ensure_bridge(self) -> None:
        bridge = self.cluster.bridge
        existing = self.runner.run(
            ["ip", "-j", "link", "show", bridge], check=False
        )
        if existing.returncode != 0:
            self.runner.run(["ip", "link", "add", bridge, "type", "bridge"])
        self.runner.run(
            [
                "ip",
                "addr",
                "replace",
                f"{self.cluster.host_ip}/{self.cluster.subnet.prefixlen}",
                "dev",
                bridge,
            ]
        )
        self.runner.run(["ip", "link", "set", bridge, "up"])

    def _enable_forwarding(self) -> None:
        self.runner.run(["sysctl", "-w", "net.ipv4.ip_forward=1"])
